name: Heroku Awake

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        env:
          HEROKU_URL: ${{ URL }}
        with:
          URL: echo "$HEROKU_URL"
